# @package _global_

defaults:
  - classification_base


dataset:
  name: custom
  simple_cls:
    _target_: datasets.custom.custom.CustomSimpleDataset

  set_cls:
    _target_: datasets.custom.custom.CustomSetDataset

backbone:
  _target_: backbones.fcnet.FCNet
  layer_dim: [ 512, 512]

train_classes: 5

n_way: 3
n_shot: 5
n_query: 15

