defaults:
  - meta_base

cls:
  _target_: methods.settoset.feat.FEAT
  n_head: 4
  dropout: 0.1
  dim_feedforward: 512
  score:
    _target_: methods.settoset.settoset.CosineSimilarityScore

name: feat